# Generated by Django 4.1.2 on 2022-11-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_laboratorio_fechacreacion_laboratorio_usuarioactivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='usuarioActivo',
        ),
    ]
