# Generated by Django 4.1.2 on 2022-10-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='images/usuarios/default.png', upload_to='images/usuarios'),
        ),
    ]
