# Generated by Django 4.1.2 on 2022-10-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=60, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numDocumento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Documento'),
        ),
    ]
