# Generated by Django 4.1.2 on 2022-11-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alias',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Alias usuario'),
        ),
    ]
