# Generated by Django 4.1.2 on 2022-11-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_fechacreacion_usuario_usuarioactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuarioActivo',
            field=models.CharField(default='admin', max_length=15),
        ),
    ]
