# Generated by Django 4.1.2 on 2022-11-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_usuario_usuarioactivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuarioActivo',
        ),
    ]
