# Generated by Django 4.1.2 on 2022-10-26 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0003_medicamento_consumodiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='contador',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Contador'),
        ),
    ]
