# Generated by Django 4.1.2 on 2022-10-26 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0005_alter_medicamento_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='consumoDiario',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumo Diario'),
        ),
    ]
