# Generated by Django 4.1.2 on 2022-10-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0006_alter_medicamento_consumodiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='fechaDosis',
            field=models.DateField(help_text='DD/MM/AAAA', null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
