# Generated by Django 4.1.2 on 2022-10-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0008_alter_medicamento_fechadosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='fechaDosis',
        ),
    ]
