# Generated by Django 4.1.2 on 2022-10-27 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0009_remove_medicamento_fechadosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='fechaDosis',
            field=models.DateField(default=datetime.date.today, help_text='AAAA/MM/DD', null=True, verbose_name='Fecha Dosis'),
        ),
    ]
