# Generated by Django 4.1.2 on 2022-10-29 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0010_medicamento_fechadosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='alerta',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alerta'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dosis a Administrar'),
        ),
    ]
