# Generated by Django 4.1.2 on 2022-10-30 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0011_medicamento_alerta_alter_medicamento_dosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fechaDosis',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha Dosis'),
        ),
    ]
