# Generated by Django 4.1.2 on 2022-10-31 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0013_medicamento_ultimadosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='ultimaDosis',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Hora última dosis'),
        ),
    ]
