# Generated by Django 4.1.2 on 2022-10-31 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0016_alter_medicamento_ultimadosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='ultimaDosis',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 20, 8, 30, 84924), null=True, verbose_name='Hora última dosis'),
        ),
    ]
