# Generated by Django 4.1.2 on 2022-11-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0019_medicamento_fechacreacion_medicamento_usuarioactivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='usuarioActivo',
        ),
    ]
