# Generated by Django 4.1.2 on 2022-10-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='numDocumento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número Documento'),
        ),
    ]
