# Generated by Django 4.1.2 on 2022-11-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nacionalidad', '0002_nacionalidad_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nacionalidad',
            name='usuarioActivo',
        ),
    ]
