# Generated by Django 4.1.2 on 2022-11-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargo_fechacreacion_cargo_usuarioactivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='usuarioActivo',
        ),
    ]
